// <auto-generated />
using System;
using Customer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Customer.Infrastructure.Migrations;

[DbContext(typeof(CustomerContext))]
[Migration("20240624023046_Initial")]
partial class Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Customer.Domain.Entities.Customer", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<DateTime>("Birthdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("City")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<decimal>("Deposit")
                    .HasColumnType("decimal(18,2)");

                b.Property<bool>("Gender")
                    .HasColumnType("boolean");

                b.Property<bool>("IsNewCustomer")
                    .HasColumnType("boolean");

                b.Property<DateTime?>("LastModifiedDate")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Birthdate");

                b.HasIndex("City");

                b.HasIndex("Deposit");

                b.HasIndex("Gender");

                b.HasIndex("IsNewCustomer");

                b.ToTable("Customers");
            });
#pragma warning restore 612, 618
    }
}
